[package]
name = "local-stack-proof-persistence-format"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
local-stack-proof-application = { path = "../application" }
local-stack-proof-domain = { path = "../domain" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[lints]
workspace = true
