[package]
name = "local-stack-proof-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum = "0.8.9"
dotenvy = "0.15.7"
local-stack-proof-application = { path = "../../crates/application" }
local-stack-proof-transport-http = { path = "../../crates/transport-http" }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread"] }

[lints]
workspace = true
